# Variables to be overwritten or stored in Ansible Vault for secrets
use_docker: true
repo_url: 'https://github.com/abhingram/deals247.git'
app_dir: '/var/www/deals247'
node_version: '20'

# DB - placeholders only; secrets should be in vault
db_host: 'srv994.hstgr.io'
db_port: 3306
db_name: 'u515501238_deals247_db'
db_user: 'deals247_user'
# db_password should be stored in Ansible Vault
# db_password: 'REPLACE_WITH_VAULT'

db_ssl: false
# db_ssl_ca_path: '/etc/ssl/certs/hostinger_mysql_ca.pem'

# Certificate email
cert_email: 'admin@deals247.online'
